POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "cassandra-sink-reviews-by-rating",
  "config": {
    "connector.class": "io.confluent.connect.cassandra.CassandraSinkConnector",
    "tasks.max": "1",
    "topics": "reviews",

    "cassandra.contact.points": "cassandra-node1",
    "cassandra.port": "9042",
    "cassandra.local.datacenter": "datacenter1",
    "cassandra.keyspace": "ecommerce_reviews",
    "cassandra.table": "reviews_by_rating",
    "confluent.topic.bootstrap.servers": "kafka-broker:29092",
    "confluent.topic.replication.factor": "1",
    "cassandra.topic.key.field.mapping": "rating=rating,product_id=product_id,user_id=user_id",
    "cassandra.topic.value.field.mapping": "rating=rating,product_id=product_id,user_id=user_id,title=title,description=description",
    "cassandra.query.timeout": "PT10S",
    "cassandra.socket.timeout": "PT10S",

    "table.name.format": "reviews_by_rating",

    "parse.key": "true",

    "key.converter": "io.confluent.connect.avro.AvroConverter",
    "key.converter.schema.registry.url": "http://schema-registry:8085",

    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8085"
  }
}
###
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "cassandra-sink-product-review-avg-windowed",
  "config": {
    "connector.class": "io.confluent.connect.cassandra.CassandraSinkConnector",
    "tasks.max": "1",
    "topics": "REV_AVG_WIN",

    "cassandra.contact.points": "cassandra-node1",
    "cassandra.port": "9042",
    "cassandra.local.datacenter": "datacenter1",
    "cassandra.keyspace": "product_analytics",
    "cassandra.table": "product_review_avg_windowed_pkpid",

    "pk.mode": "record_key",
    "pk.fields": "PRODUCT_ID_VAL",

    "cassandra.topic.key.field.mapping": "PRODUCT_ID_VAL=product_id",
    "cassandra.topic.value.field.mapping": "WINDOW_START=window_start,WINDOW_END=window_end,TOTAL_UNIQUE_USER_REVIEWS=total_unique_user_reviews,AVERAGE_RATING=average_rating",

    "transforms": "CreateKey",
    "transforms.CreateKey.type": "org.apache.kafka.connect.transforms.ValueToKey",
    "transforms.CreateKey.fields": "PRODUCT_ID_VAL",

    "cassandra.query.timeout": "PT60S",
    "cassandra.socket.timeout": "PT60S",
    "cassandra.connection.timeout": "PT60S",
    "cassandra.request.timeout": "PT60S",

    "cassandra.max.concurrent.requests": "500",
    "cassandra.max.requests.per.connection": "1024",

    "errors.tolerance": "all",
    "errors.log.enable": "true",
    "errors.log.include.messages": "true",

    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "io.confluent.connect.avro.AvroConverter",
    "value.converter.schema.registry.url": "http://schema-registry:8081",

    "confluent.topic.bootstrap.servers": "kafka-broker:29092",
    "confluent.topic.replication.factor": "1"
  }
}

###
GET http://localhost:8083/connectors/cassandra-sink-product-review-avg-windowed/status/

###
# DELETE http://localhost:8083/connectors/cassandra-sink-product-review-avg-windowed/
###
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "postgres-debezium-connector",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "tasks.max": "1",
    "database.hostname": "ep-solitary-rain-agpdcc7p-pooler.c-2.eu-central-1.aws.neon.tech",
    "database.port": "5432",
    "database.user": "replication_product",
    "database.password": "npg_0KvE2pJDPRra",
    "database.dbname": "neondb",
    "database.server.name": "neondb",
    "table.include.list": "public.Product",
    "plugin.name": "pgoutput",
    "publication.name": "dbz_publication",
    "slot.name": "debezium",
    "database.sslmode": "require"
  }
}

###
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "s3-bronze-sink",
  "config": {
    "connector.class": "io.confluent.connect.s3.S3SinkConnector",
    "tasks.max": "1",

    "topics": "neondb.public.Product",

    "s3.bucket.name": "datalake",
    "s3.region": "us-east-1",

    "store.url": "http://minio:9000",
    "s3.path.style.access.enabled": "true",

    "aws.access.key.id": "minioadmin",
    "aws.secret.access.key": "minioadmin",

    "storage.class": "io.confluent.connect.s3.storage.S3Storage",
    "format.class": "io.confluent.connect.s3.format.json.JsonFormat",

    "topics.dir": "bronze",
    "flush.size": "1",
    "schema.compatibility": "NONE",
    "behavior.on.null.values": "ignore",

    "key.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "key.converter.schemas.enable": "false",
    "value.converter.schemas.enable": "false"
  }
}

###
GET http://localhost:8083/connectors/postgres-debezium-connector/status/
###
###
GET http://localhost:8083/connectors/s3-bronze-sink/status/

###
# curl -X DELETE http://localhost:8083/connectors/cassandra-sink-reviews-by-rating
GET http://localhost:8083/connectors/cassandra-sink-reviews-by-rating/status/

###
# curl -X POST http://localhost:8083/connectors/postgres-debezium-connector/restart
POST http://localhost:8083/connectors/postgres-debezium-connector/restart

###
DELETE http://localhost:8083/connectors/cassandra-sink-reviews-by-rating/

###
DELETE http://localhost:8083/connectors/s3-bronze-sink/

###
DELETE http://localhost:8083/connectors/postgres-debezium-connector/



# curl -X GET http://localhost:8083/connectors/
###
GET http://localhost:8083/connectors

###
GET http://localhost:8083/connector-plugins

###
GET http://localhost:8083/connectors/8083/connectors/cassandra-sink-reviews-by-rating/restart
###

# curl -s http://localhost:8085/subjects
GET http://localhost:8085/subjects

###
GET http://localhost:8085/subjects/AVG_REV-value/versions/1

###
# curl http://schema-registry:8085/subjects/PRODUCT_REVIEW_AVG_WINDOWED_M-value/versions/latest
GET http://localhost:8085/subjects/REV_AVG_WIN-value/versions/1


# curl http://schema-registry:8085/subjects/PRODUCT_REVIEW_AVG_WINDOWED_M-value/versions/latest
GET http://localhost:8085/subjects/PRODUCT_REVIEW_AVG_WINDOWED_M-value/versions/2

###

# curl -X DELETE http://localhost:8085/subjects/product-reviews-key
#curl -X DELETE http://localhost:8085/subjects/product-reviews-value
DELETE http://localhost:8085/subjects/reviews-value

###